services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    network_mode: host

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@localhost:27017/
      ME_CONFIG_BASICAUTH: false
    network_mode: host

  # Mongo Express for storage management (connecting to mongo-storage)
  # mongo-express-storage:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081 # Expose mongo-express UI port
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
  #     ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo-storage:27017/ # Point to mongo-storage service
  #     ME_CONFIG_BASICAUTH: false

  # Storage Management Service
  # storage-mgmt-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/storage-mgmt-service/Dockerfile
  #     target: development
  #   command: npm run start:dev storage-mgmt-service
  #   env_file:
  #     - ./apps/storage-mgmt-service/.env
  #   depends_on:
  #     - mongo-user
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #     - $HOME/credentials/cc-final-445817-db19ad7f3f68.json:/gcp/creds.json:ro
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
  #   ports:
  #     - '3000:3000'
  #   network_mode: host

  # # User Management Service
  # user-mgmt-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/user-acc-mgmt-service/Dockerfile
  #     target: development
  #   command: npm run start:dev user-mgmt-service
  #   env_file:
  #     - ./apps/user-acc-mgmt-service/.env
  #   depends_on:
  #     - mongo-user
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #     - $HOME/credentials/cc-final-445817-db19ad7f3f68.json:/gcp/creds.json:ro
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
  #   ports:
  #     - '4000:4000'
  #   network_mode: host

  # # Usage Management Service
  # usage-mgmt-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/usage-mgmt-service/Dockerfile
  #     target: development
  #   command: npm run start:dev usage-mgmt-service
  #   env_file:
  #     - ./apps/usage-mgmt-service/.env
  #   depends_on:
  #     - mongo-user
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #     - $HOME/credentials/cc-final-445817-db19ad7f3f68.json:/gcp/creds.json:ro
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
  #   ports:
  #     - '5000:5000'
  #   network_mode: host
